# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# For single-page-app routing: serve index.html for all paths
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
