[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"   # any 20.x LTS
  NPM_FLAGS = ""
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

